version: 0.2
phases:
  install:
    commands:
      - yum -y update
      - yum -y install ruby
      - yum -y install zip
      - yum -y install wget
      - yum -y install awscli
      - yum -y install git
      - git clone https://github.com/sathavahanadevops/awslamdacodepipeline.git
      - cd awslamdacodepipeline
      - touch test.lib
      - rm -rf README.md buildspec.yml
      - aws s3 ls
      - aws s3 mv lamda.json s3://cfstacklamda
      - rm -rf lamda.json
      - cd ..
      - zip -r lamdacodetest.zip awslamdacodepipeline
      - aws s3 ls
      - aws s3 mv lamdacodetest.zip s3://ngnixcodebuild
      - wget https://cfstacklamda.s3.amazonaws.com/lamda.json
      - pwd
      - aws cloudformation update-stack --stack-name lamdacodetest --template-url https://cfstacklamda.s3.amazonaws.com/lamda.json
  pre_build:
    commands:
      - echo prebuild
  build:
    commands:
      - echo buildstarted  
  post_build:
     commands:
       - echo postbuild
artifacts:
  files:
    - '**/*'
